name: Build Docker Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build Frontend Docker Image
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Frontend Docker image
      run: |
        docker build -f Dockerfile.frontend -t s3-commando-frontend:latest .
        echo "✅ Frontend Docker image built successfully!"
        docker images s3-commando-frontend:latest

  build-server:
    runs-on: ubuntu-latest
    name: Build Server Docker Image
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Server Docker image
      run: |
        docker build -f Dockerfile.server -t s3-commando-server:latest .
        echo "✅ Server Docker image built successfully!"
        docker images s3-commando-server:latest

  build-summary:
    runs-on: ubuntu-latest
    name: Build Summary
    needs: [build-frontend, build-server]
    
    steps:
    - name: Build Summary
      run: |
        echo "🎉 Docker Build Summary"
        echo "========================"
        echo "✅ Frontend image: s3-commando-frontend:latest"
        echo "✅ Server image: s3-commando-server:latest"
        echo ""
        echo "Both images have been built successfully!"
        echo "Images are not pushed to any registry (as requested)."
        echo "To push images later, you can modify this workflow or create a separate one." 